# Generated by Django 5.0.2 on 2026-02-22 12:29

import django.db.models.deletion
import gestaoTarefas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('idTarefa', models.BigIntegerField(default=gestaoTarefas.models.gerar_id_tarefa, editable=False, primary_key=True, serialize=False, verbose_name='ID da Tarefa')),
                ('tarefa', models.CharField(max_length=255, verbose_name='Nome da Tarefa')),
                ('itemTarefa', models.CharField(max_length=255, verbose_name='Item da Tarefa')),
                ('dataDistribuicaoTarefa', models.DateField(verbose_name='Data de Distribuição')),
                ('prazoRealizacaoTarefa', models.DateField(verbose_name='Prazo de Realização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('statusTarefa', models.CharField(choices=[('No prazo', 'No prazo'), ('Atrasada', 'Atrasada'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='No prazo', max_length=20, verbose_name='Status')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
        ),
    ]
